export const nameTranslations = {
  "李思同": "Li Si Tong",
  "尹成雨": "Yin Cheng Yu",
  "徐子晗": "Xu Zi Han",
  "丁子烨": "Ding Zi Ye",
  "杨珂妍": "Yang Ke Yan",
  "张亚楠": "Zhang Ya Nan",
  "申鸿雁": "Shen Hong Yan",
  "曹佳乐": "Cao Jia Le",
  "苏振颉": "Su Zhen Jie",
  "张子怡": "Zhang Zi Yi",
  "郑嘉宁": "Zheng Jia Ning",
  "刘瑞娜": "Liu Rui Na",
  "崔广明": "Cui Guang Ming",
  "江灿家": "Jiang Can Jia",
  "邢王润": "Xing Wang Run",
  "丁超维": "Ding Chao Wei",
  "卢泽宇": "Lu Ze Yu",
  "冯澍": "Feng Shu",
  "李姝怡": "Li Shu Yi",
  "雷凯栋": "Lei Kai Dong",
  "贾世豪": "Jia Shi Hao",
  "刘洋": "Liu Yang",
  "王竹": "Wang Zhu",
  "王钟乐": "Wang Zhong Le",
  "张志宏": "Zhang Zhi Hong",
  "刘媛媛": "Liu Yuan Yuan",
  "崔宸玮": "Cui Chen Wei",
  "成果": "Cheng Guo",
  "任越": "Ren Yue",
  "高宇杰": "Gao Yu Jie",
  "高开翼": "Gao Kai Yi",
  "李娇": "Li Jiao",
  "薛雨婷": "Xue Yu Ting",
  "王瑛炜": "Wang Ying Wei",
  "郭一诺": "Guo Yi Nuo",
  "刘倩": "Liu Qian",
  "李思宇": "Li Si Yu",
  "张浩哲": "Zhang Hao Zhe",
  "刘宇华": "Liu Yu Hua",
  "王镜荣": "Wang Jing Rong",
  "王竹青": "Wang Zhu Qing",
  "任毅": "Ren Yi",
  "李浩楠": "Li Hao Nan",
  "宋欣怡": "Song Xin Yi",
  "秦思思": "Qin Si Si",
  "姚屹峻": "Yao Yi Jun",
  "曹书渊": "Cao Shu Yuan",
  "孙浩博": "Sun Hao Bo",
  "赵玲瑞": "Zhao Ling Rui",
  "刘宇": "Liu Yu",
  "闫子薇": "Yan Zi Wei",
  "郝泓淘": "Hao Hong Tao",
  "席懿鹏": "Xi Yi Peng",
  "任向洁": "Ren Xiang Jie",
  "赵映祯": "Zhao Ying Zhen",
  "杨子豪": "Yang Zi Hao",
  "马晟": "Ma Cheng",
  "徐家彬": "Xu Jia Bin",
  "张凯皓": "Zhang Kai Hao",
  "王泽英": "Wang Ze Ying",
  "张怡": "Zhang Yi",
  "白江涛": "Bai Jiang Tao",
  "李新朋": "Li Xin Peng",
  "张豪杰": "Zhang Hao Jie",
  "王志敏": "Wang Zhi Min",
  "郭东昊": "Guo Dong Hao",
  "李平安": "Li Ping An",
  "王建淳": "Wang Jian Chun",
  "刘思懿": "Liu Si Yi",
  "王雨璇": "Wang Yu Xuan",
  "杨琳悦": "Yang Lin Yue",
  "范阳瑞": "Fan Yang Rui",
  "范姝欣": "Fan Shu Xin",
  "郜越峰": "Gao Yue Feng",
  "郭佼": "Guo Jiao",
  "尚博源": "Shang Bo Yuan",
  "宋宇航": "Song Yu Hang",
  "李婧达": "Li Jing Da",
  "毕圆圆": "Bi Yuan Yuan",
  "杜昱": "Du Yu",
  "王旭涵": "Wang Xu Han",
  "王雅婷": "Wang Ya Ting",
  "蔡雨轩": "Cai Yu Xuan",
  "刘嘉悦": "Liu Jia Yue",
  "柴竹涛": "Chai Zhu Tao",
  "王嫣然": "Wang Yan Ran",
  "侯佳鑫": "Hou Jia Xin",
  "仇伟强": "Chou Wei Qiang",
  "巨雅渊": "Ju Ya Yuan",
  "赵浩博": "Zhao Hao Bo",
  "赵姝敏": "Zhao Shu Min",
  "李鹏丽": "Li Peng Li",
  "田哲渊": "Tian Zhe Yuan",
  "王启冉": "Wang Qi Ran",
  "罗子龙": "Luo Zi Long",
  "李珺": "Li Jun",
  "李晶瑾": "Li Jing Jin",
  "高依凡": "Gao Yi Fan",
  "刘嘉瑜": "Liu Jia Yu",
  "陈佳璐": "Chen Jia Lu",
  "张钰涵": "Zhang Yu Han",
  "薛博涵": "Xue Bo Han",
  "赵文博": "Zhao Wen Bo",
  "李星依": "Li Xing Yi",
  "霍雨帅": "Huo Yu Shuai",
  "王玮烨": "Wang Wei Ye",
  "翟亿锋": "Di Yi Feng",
  "徐靖皓": "Xu Jing Hao",
  "杨嘉睿": "Yang Jia Rui",
  "王语阳": "Wang Yu Yang",
  "张佳仪": "Zhang Jia Yi",
  "郑子歆": "Zheng Zi Xin",
  "胡碧涛": "Hu Bi Tao",
  "吴亚楠": "Wu Ya Nan",
  "陈镜豪": "Chen Jing Hao",
  "高岩松": "Gao Yan Song",
  "宋晓坤": "Song Xiao Kun",
  "徐浩然": "Xu Hao Ran",
  "裴浩玥": "Pei Hao Yue",
  "王宇帆": "Wang Yu Fan",
  "张乐琦": "Zhang Le Qi",
  "王一鸣": "Wang Yi Ming",
  "崔雅欣": "Cui Ya Xin",
  "刘一帆": "Liu Yi Fan",
  "苏伟冉青": "Su Wei Ran Qing",
  "程奕丹": "Cheng Yi Dan",
  "师可莹": "Shi Ke Ying",
  "任若绮": "Ren Ruo Qi",
  "李瑛珏": "Li Ying Jue",
  "李馨雨": "Li Xin Yu",
  "李润宇": "Li Run Yu",
  "任玥": "Ren Yue",
  "范景霖": "Fan Jing Lin",
  "李俊燃": "Li Jun Ran",
  "石欣蕾": "Shi Xin Lei",
  "王淼": "Wang Miao",
  "赵依婷": "Zhao Yi Ting",
  "周乐琪": "Zhou Le Qi",
  "崔依宁": "Cui Yi Ning",
  "冯小钰": "Feng Xiao Yu",
  "赵应祁": "Zhao Ying Qi",
  "郑惜月": "Zheng Xi Yue",
  "苏湲聪": "Su Yuan Cong",
  "耿晨轩": "Geng Chen Xuan",
  "杨瑾俞": "Yang Jin Yu",
  "李嘉璐": "Li Jia Lu",
  "魏子期": "Wei Zi Qi",
  "张亦驰": "Zhang Yi Chi",
  "孙起泽": "Sun Qi Ze",
  "刘悦伟": "Liu Yue Wei",
  "李思彤": "Li Si Tong",
  "姚奕婷": "Yao Yi Ting",
  "杨筝": "Yang Zheng",
  "范子嫣": "Fan Zi Yan",
  "苏琪元": "Su Qi Yuan",
  "孙子阳": "Sun Zi Yang",
  "范照楷": "Fan Zhao Kai",
  "王蔡佳睿": "Wang Cai Jia Rui",
  "黄子涵": "Huang Zi Han",
  "宋心妍": "Song Xin Yan",
  "曹雅坤": "Cao Ya Kun",
  "张宇璇": "Zhang Yu Xuan",
  "孙可暄": "Sun Ke Xuan",
  "邢志佳": "Xing Zhi Jia",
  "郑雯静": "Zheng Wen Jing",
  "尉宇博": "Wei Yu Bo",
  "王镭珂": "Wang Lei Ke",
  "郭瑜冰": "Guo Yu Bing",
  "高正坤": "Gao Zheng Kun",
  "阎昊轩": "Yan Hao Xuan",
  "王思颖": "Wang Si Ying",
  "石翔宇": "Shi Xiang Yu",
  "王冠英": "Wang Guan Ying",
  "郭振锐": "Guo Zhen Rui",
  "孙欣蕊": "Sun Xin Rui",
  "王思淇": "Wang Si Qi",
  "穆维翔": "Mu Wei Xiang",
  "李宗桓": "Li Zong Huan",
  "刘姝含": "Liu Shu Han",
  "马博文": "Ma Bo Wen",
  "王玺": "Wang Xi",
  "张力文": "Zhang Li Wen",
  "李锦源": "Li Jin Yuan",
  "王诗语": "Wang Shi Yu",
  "陈宇妍": "Chen Yu Yan",
  "邵礼琛": "Shao Li Chen",
  "杨舒羽": "Yang Shu Yu",
  "王煜泽": "Wang Yu Ze",
  "杨司牧": "Yang Si Mu",
  "王玥瑶": "Wang Yue Yao",
  "周嘉怡": "Zhou Jia Yi",
  "杨舒涵": "Yang Shu Han",
  "义昕": "Yi Xin",
  "徐一杰": "Xu Yi Jie",
  "鞠浩茹": "Ju Hao Ru",
  "郑杨恩琪": "Zheng Yang En Qi",
  "吴贵德": "Wu Gui De",
  "马玥": "Ma Yue",
  "袁暄迪": "Yuan Xuan Di",
  "杜亿鹤": "Du Yi He",
  "李鸣羽": "Li Ming Yu",
  "徐晓潇": "Xu Xiao Xiao",
  "李菁欣": "Li Jing Xin",
  "张立安": "Zhang Li An",
  "常谦": "Chang Qian",
  "刘波良": "Liu Bo Liang",
  "陈邢睿超": "Chen Xing Rui Chao",
  "黄金雨": "Huang Jin Yu",
  "刘娜溪": "Liu Na Xi",
  "宋睿轩": "Song Rui Xuan",
  "刘瑞阳": "Liu Rui Yang",
  "范霄鸥": "Fan Xiao Ou",
  "黄明暄": "Huang Ming Xuan",
  "周佳玮": "Zhou Jia Wei",
  "张涵昱": "Zhang Han Yu",
  "高靖琛": "Gao Jing Chen",
  "乔思泽": "Qiao Si Ze",
  "田一翔": "Tian Yi Xiang",
  "彭浦轩": "Peng Pu Xuan",
  "张纪涛": "Zhang Ji Tao",
  "王沛琦": "Wang Pei Qi",
  "房国栋": "Fang Guo Dong",
  "方昕瑶": "Fang Xin Yao",
  "高慧钰": "Gao Hui Yu",
  "韩腾飞": "Han Teng Fei",
  "王翔宇": "Wang Xiang Yu",
  "张姝怡": "Zhang Shu Yi",
  "李璞淇": "Li Pu Qi",
  "安奕璇": "An Yi Xuan",
  "卫东恺": "Wei Dong Kai",
  "张子魏": "Zhang Zi Wei",
  "赵欣逸": "Zhao Xin Yi",
  "王丞钰": "Wang Cheng Yu",
  "罗紫宁": "Luo Zi Ning",
  "赵芯璇": "Zhao Xin Xuan",
  "崔晨欣": "Cui Chen Xin",
  "张旭苒": "Zhang Xu Ran",
  "褚泽辉": "Chu Ze Hui",
  "刘亭阅": "Liu Ting Yue",
  "赵鹏宇": "Zhao Peng Yu",
  "梁妙婷": "Liang Miao Ting",
  "布洪旭": "Bu Hong Xu",
  "郝源敏": "Hao Yuan Min",
  "朱梦媛": "Zhu Meng Yuan",
  "齐巍泽": "Qi Wei Ze",
  "张宇焓": "Zhang Yu Han",
  "王璟玥": "Wang Jing Yue",
  "刘芃杉": "Liu Peng Shan",
  "韩心晖": "Han Xin Hui",
  "孙家兴": "Sun Jia Xing",
  "庞一凡": "Pang Yi Fan",
  "申媛媛": "Shen Yuan Yuan",
  "李嘉慧": "Li Jia Hui",
  "徐璨": "Xu Can",
  "刘岐": "Liu Qi",
  "王懿煊": "Wang Yi Xuan",
  "申帅宇": "Shen Shuai Yu",
  "靳德明": "Jin De Ming",
  "梁一凡": "Liang Yi Fan",
  "郭家兴": "Guo Jia Xing",
  "王宇亭": "Wang Yu Ting",
  "张浩东": "Zhang Hao Dong",
  "张耀天": "Zhang Yao Tian",
  "蓝靖凯": "Lan Jing Kai",
  "董浩源": "Dong Hao Yuan",
  "沈乐怡": "Shen Le Yi",
  "冯天勤": "Feng Tian Qin",
  "吉鑫宇": "Ji Xin Yu",
  "殷嘉琳": "Yin Jia Lin",
  "于水怡": "Yu Shui Yi",
  "赵国瑞": "Zhao Guo Rui",
  "游雅琪": "You Ya Qi",
  "魏子谞": "Wei Zi Xu",
  "丁子轩": "Ding Zi Xuan",
  "李思颀": "Li Si Qi",
  "ZUO BOYU": "Zuo Boyu",
  "田宛璐": "Tian Wan Lu",
  "冀浩洋": "Ji Hao Yang",
  "贾烨君": "Jia Ye Jun",
  "杜一帆": "Du Yi Fan",
  "朱嘉潞": "Zhu Jia Lu",
  "贝显鹏": "Bei Xian Peng",
  "魏浩楠": "Wei Hao Nan",
  "司新垚": "Si Xin Yao",
  "高琪": "Gao Qi",
  "方爽惠": "Fang Shuang Hui",
  "景天瑞": "Jing Tian Rui",
  "朱堃瑶": "Zhu Kun Yao",
  "杨启航": "Yang Qi Hang",
  "刘津羽": "Liu Jin Yu",
  "王潇": "Wang Xiao",
  "高婕菲": "Gao Jie Fei",
  "贾思莹": "Jia Si Ying",
  "李怡馨": "Li Yi Xin",
  "刘含卓": "Liu Han Zhuo",
  "李一博": "Li Yi Bo",
  "王姝懿": "Wang Shu Yi",
  "乔子宸": "Qiao Zi Chen",
  "畅子文": "Chang Zi Wen",
  "梁文博": "Liang Wen Bo",
  "杜笑宇": "Du Xiao Yu",
  "马佳敏": "Ma Jia Min",
  "武卓颖": "Wu Zhuo Ying",
  "蔡林希": "Cai Lin Xi",
  "郝厚哲": "Hao Hou Zhe",
  "李欣洁": "Li Xin Jie",
  "闫鹏宇": "Yan Peng Yu",
  "靳辰钰": "Jin Chen Yu",
  "张泽华": "Zhang Ze Hua",
  "马祯嵘": "Ma Zhen Rong",
  "李宇潇": "Li Yu Xiao",
  "潘欣玥": "Pan Xin Yue",
  "康昊萤": "Kang Hao Ying",
  "何宇翔": "He Yu Xiang",
  "段晓宁": "Duan Xiao Ning",
  "吴凯": "Wu Kai",
  "王炎博": "Wang Yan Bo",
  "王鸣欣": "Wang Ming Xin",
  "任佳慧": "Ren Jia Hui",
  "赵宇婷": "Zhao Yu Ting",
  "张宇祺": "Zhang Yu Qi",
  "黑玉璇": "Hei Yu Xuan",
  "段浩恺": "Duan Hao Kai",
  "冯焱琳": "Feng Yan Lin",
  "田宇航": "Tian Yu Hang",
  "梁锡全": "Liang Xi Quan",
  "薛皓天": "Xue Hao Tian",
  "陈志凯": "Chen Zhi Kai",
  "郑宇彤": "Zheng Yu Tong",
  "张博文": "Zhang Bo Wen",
  "赵宇豪": "Zhao Yu Hao",
  "张悦悦": "Zhang Yue Yue",
  "嵇楷航": "Ji Kai Hang",
  "吴卓阳": "Wu Zhuo Yang",
  "王茹": "Wang Ru",
  "王嘉怡": "Wang Jia Yi",
  "王艺陶": "Wang Yi Tao",
  "李佳烨": "Li Jia Ye",
  "李翔宇": "Li Xiang Yu",
  "王祉涵": "Wang Zhi Han",
  "梁译丹": "Liang Yi Dan",
  "史怀荣": "Shi Huai Rong",
  "逯彦君": "Lu Yan Jun",
  "马郭玺": "Ma Guo Xi",
  "杨佳欣": "Yang Jia Xin",
  "郑宇凡": "Zheng Yu Fan",
  "鞠芳宇": "Ju Fang Yu",
  "徐丰芸": "Xu Feng Yun",
  "刘丹宇": "Liu Dan Yu",
  "薛卓凡": "Xue Zhuo Fan",
  "李思逾": "Li Si Yu",
  "逯桐": "Lu Tong",
  "孙炳烜": "Sun Bing Xuan",
  "魏于婷": "Wei Yu Ting",
  "翟娅萱": "Di Ya Xuan",
  "张轶雯": "Zhang Yi Wen",
  "崔怡凯": "Cui Yi Kai",
  "赵以彤": "Zhao Yi Tong",
  "张天翔": "Zhang Tian Xiang",
  "张琦曼": "Zhang Qi Man",
  "王晁辉": "Wang Chao Hui",
  "刘子祯": "Liu Zi Zhen",
  "杨育璇": "Yang Yu Xuan",
  "李馨仪": "Li Xin Yi",
  "张美卉": "Zhang Mei Hui",
  "闫泽贤": "Yan Ze Xian",
  "王宇欣": "Wang Yu Xin",
  "宋雨潼": "Song Yu Tong",
  "徐伟齐": "Xu Wei Qi",
  "张振": "Zhang Zhen",
  "栗欣仪": "Li Xin Yi",
  "闫依晨": "Yan Yi Chen",
  "常斯源": "Chang Si Yuan",
  "LI TING李婷": "Li Ting",
  "武汶怡": "Wu Wen Yi"
};

export const backUpTranslations = {
  "湖北省武汉市新洲区": "Hu Bei Province WuHan City Xin Zhou Qu",
  "河南省信阳市息县": "HeNan Province XinYang City XiXian",
  "河南省新乡市长垣县": "HeNan Province XinXiang City ZhangYuan Xian",
  "河南省焦作市沁阳市": "HeNan Province JiaoZuo City QinYang City",
  "河南省新乡市封丘县": "HeNan Province XinXiang City FengQiu Xian",
  "河南省鹤壁市山城区": "HeNan Province HeBi City Shan Cheng Qu",
  "河南省安阳市林州市": "HeNan Province AnYang City Lin Zhou City",
  "河南省安阳市内黄县": "HeNan Province AnYang City Nei Huang Xian",
  "福建省泉州市安溪县": "FuJian Province QuanZhou City An Xi Xian",
  "安徽省阜阳市阜南县": "AnHui Province FuYang City Fu Nan Xian",
  "福建省莆田市涵江区": "FuJian Province PuTian City Han Jiang Qu",
  "安徽省阜阳市临泉县": "AnHui Province FuYang City Lin Quan Xian",
  "安徽省阜阳市涡阳县": "AnHui Province FuYang City Wo Yang Xian",
  "江苏省南通市海门市": "JiangSu Province NanTong City Hai Men City",
  "辽宁省大连市瓦房店市": "LiaoNing Province DaLian City Wa Fang Dian City",
  "山西省临汾地区襄汾县": "ShanXi Province LinFen Area XiangFen Xian",
  "山西省临汾地区霍州市": "ShanXi Province LinFen Area Huo Zhou City",
  "山西省临汾地区临汾市": "ShanXi Province LinFen Area Lin Fen City",
  "山西省晋中地区平遥县": "ShanXi Province JinZhong Area Ping Yao Xian",
  "山西省忻州地区兴县": "ShanXi Province XinZhou Area Xing Xian",
  "山西省忻州地区文水县": "ShanXi Province XinZhou Area Wen Shui Xian",
  "山西省忻州地区静乐县": "ShanXi Province XinZhou Area Jing Le Xian",
  "山西省忻州地区繁峙县": "ShanXi Province XinZhou Area Fan Zhi Xian",
  "山西省忻州地区五台县": "ShanXi Province XinZhou Area Wu Tai Xian",
  "山西省晋城市怀仁县": "ShanXi Province JinCheng City Huai Ren Xian",
  "山西省晋城市山阴县": "ShanXi Province JinCheng City Shan Yin Xian",
  "山西省长治市沁源县": "ShanXi Province Zhang Zhi City Qin Yuan Xian",
  "山西省长治市武乡县": "ShanXi Province Zhang Zhi City Wu Xiang Xian",
  "山西省长治市长子县": "ShanXi Province Zhang Zhi City Zhang Zi Xian",
  "山西省阳泉市平定县": "ShanXi Province Yang Quan City Ping Ding Xian",
  "山西省长治市屯留县": "ShanXi Province Zhang Zhi City Tun Liu Xian",
  "山西省阳泉市矿区": "ShanXi Province YangQuan City Kuang Qu",
  "山西省阳泉市城区": "ShanXi Province YangQuan City Cheng Qu",
  "山西省大同市城区": "ShanXi Province DaTong City Cheng Qu",
  "山西省大同市大同县": "ShanXi Province DaTong City Da Tong Xian",
  "山西省太原市古交市": "ShanXi Province TaiYuan City Gu Jiao City",
  "山西省太原市娄烦县": "ShanXi Province TaiYuan City Lou Fan Xian",
  "山西省太原市阳曲县": "ShanXi Province TaiYuan City Yang Qu Xian",
  "山西省太原市晋源区": "ShanXi Province TaiYuan City Jin Yuan Qu",
  "山西省太原市万柏林区": "ShanXi Province TaiYuan City Wan Bo Lin Qu",
  "山西省太原市尖草坪区": "ShanXi Province TaiYuan City Jian Cao Ping Qu",
  "山西省太原市杏花岭区": "ShanXi Province TaiYuan City Xing Hua Ling Qu",
  "山西省太原市迎泽区": "ShanXi Province TaiYuan City YingZe Qu",
  "山西省太原市小店区": "ShanXi Province TaiYuan City XiaoDian Qu",
  "河北省邯郸市永年县": "HeBei Province HanDan City YongNian Xian",
  "河北省沧州市海兴县": "HeBei Province CangZhou City HaiXing Xian",
  "河北省邯郸市大名县": "HeBei Province HanDan City DaMing Xian",
  "河北省邢台市巨鹿县": "HeBei Province XingTai City JuLu Xian",
  "北京市东城区": "BeiJing City DongCheng Qu"
};